declare module '@editorjs/table'
declare module '@editorjs/list'
declare module '@editorjs/code'
declare module '@editorjs/image'
declare module '@editorjs/header'
declare module '@firstcontributions/editorjs-codeflask'
